package com.teamderpy.victusludus.game.starcluster;

public enum EnumStarType {
	DUST,
	BROWN_DWARF,
	DEAD_BROWN_DWARF,
	PROTOSTAR,
	MAIN_SEQUENCE,
	RED_DWARF,
	BLUE_DWARF,
	WHITE_DWARF,
	HELIUM_WHITE_DWARF,
	BLACK_DWARF,
	SUB_GIANT,
	GIANT,
	BRIGHT_GIANT,
	SUPER_GIANT,
	HYPER_GIANT,
	WOLF_RAYET_STAR,
	PULSAR,
	NEUTRON_STAR,
	BLACK_HOLE,
	PLANETARY_NEBULA,
	SUPER_NOVA_TYPE_Ib,
	SUPER_NOVA_TYPE_Ic,
	SUPER_NOVA_TYPE_IIP,
	SUPER_NOVA_TYPE_IIL;
}
